# Generated by Django 3.1.14 on 2022-04-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_emotion_data_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_data',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotion_data',
            name='gender',
            field=models.CharField(default='Ingen data', max_length=10),
        ),
    ]
