# Generated by Django 3.1.14 on 2022-04-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20220428_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion_data',
            name='age',
        ),
        migrations.RemoveField(
            model_name='emotion_data',
            name='gender',
        ),
    ]
