# Generated by Django 3.1.14 on 2022-04-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20220428_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_data',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
