# Generated by Django 3.1.14 on 2022-04-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_emotion_data_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion_data',
            name='age',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
