# Generated by Django 3.1.14 on 2022-04-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20220428_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion_data',
            name='age',
        ),
    ]
