# Generated by Django 3.1.14 on 2022-04-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_emotion_data_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_data',
            name='gender',
            field=models.CharField(default='n/a', max_length=15),
        ),
    ]
