# Generated by Django 3.1.14 on 2022-10-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='koncentrationsevne',
        ),
    ]
