# Generated by Django 3.1.14 on 2022-02-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Testing1', max_length=20)),
                ('faces', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('angry', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('disgusted', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fearful', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('happy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('neutral', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('surprised', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
