# Generated by Django 3.1.14 on 2022-02-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion_data',
            name='title',
            field=models.CharField(default='Testing1', max_length=150),
        ),
    ]
