# Generated by Django 3.1.14 on 2022-03-14 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_remove_emotion_data_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gaze_data',
            old_name='computer',
            new_name='down',
        ),
        migrations.RenameField(
            model_name='gaze_data',
            old_name='iphone',
            new_name='screen',
        ),
        migrations.RenameField(
            model_name='gaze_data',
            old_name='keyboard',
            new_name='up',
        ),
        migrations.AddField(
            model_name='gaze_data',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
