# Generated by Django 3.1.14 on 2022-02-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220223_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulse_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Testing2', max_length=150, unique=True)),
                ('avg_pulse', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
