# Generated by Django 3.1.14 on 2022-04-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_emotion_data_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion_data',
            name='data',
        ),
    ]
