# Generated by Django 3.1.14 on 2022-04-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_emotion_data_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_data',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
