# Generated by Django 3.1.14 on 2022-05-05 09:35

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_emotion_data_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_data',
            name='data',
            field=picklefield.fields.PickledObjectField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
