# Generated by Django 3.1.14 on 2022-04-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fag',
            field=models.CharField(choices=[(1, 'Informatik'), (2, 'Samfundsfag')], default='n/a', max_length=20),
        ),
    ]
