# Generated by Django 3.1.14 on 2022-04-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220428_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alder',
            field=models.IntegerField(default=0),
        ),
    ]
