# Generated by Django 3.1.14 on 2022-05-19 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gaze_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(default=0)),
                ('up', models.IntegerField(default=0)),
                ('screen', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('data', models.JSONField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='n/a', max_length=15)),
                ('faces', models.IntegerField(default=0)),
                ('angry', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('disgusted', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fearful', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('happy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('neutral', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('surprised', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('dominant', models.CharField(default='neutral', max_length=15)),
                ('data', models.JSONField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
