# Generated by Django 3.1.14 on 2022-03-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion_data',
            name='data',
        ),
    ]
