# Generated by Django 3.1.14 on 2022-12-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_delete_gaze_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion_data',
            name='angry',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='emotion_data',
            name='disgusted',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='emotion_data',
            name='fearful',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='emotion_data',
            name='happy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='emotion_data',
            name='neutral',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='emotion_data',
            name='sad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='emotion_data',
            name='surprised',
            field=models.FloatField(default=0),
        ),
    ]
