# Generated by Django 3.1.14 on 2022-04-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220424_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fag',
            field=models.CharField(default='n/a', max_length=20),
        ),
    ]
