# Generated by Django 3.1.14 on 2022-02-23 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('accounts', '0002_auto_20220223_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='emotion_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.emotion_data'),
        ),
    ]
