# Generated by Django 3.1.14 on 2022-04-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220428_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alder',
            field=models.CharField(default='n/a', max_length=20),
        ),
    ]
