# Generated by Django 3.1.14 on 2022-04-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220428_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='alder',
        ),
    ]
