# Generated by Django 3.1.14 on 2022-04-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_alder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alder',
            field=models.IntegerField(default=0),
        ),
    ]
